# Generated by Django 5.2.10 on 2026-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_created_at_notification_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
