# Generated by Django 5.2.10 on 2026-02-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_active',
        ),
    ]
