# Generated by Django 5.2.10 on 2026-02-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orderitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Jaman'), (2, '2 - Qanaatlandırarsız'), (3, '3 - Jaqsı'), (4, '4 - Júdá jaqsı'), (5, '5 - Ála')]),
        ),
    ]
